#!/bin/bash
#python3 test2.py > TEMPRAZZBALL

teams=( 2070ParadigmShift TheSydneyWombats BaseballBat Steerbrenner \
        BashBrotherRedux ThanesTeam NicksGloriousTeam Senators \
        JamesSwagTeam NightWatcher OlympicGold Spartans )

for i in {1..12}
do
  python3 $HOME/Documents/FantasyBaseballApplications/test.py $i B sum > "$HOME/Documents/FantasyBaseballApplications/\
Output/${teams[$i-1]}"
  python3 $HOME/Documents/FantasyBaseballApplications/test.py $i B list >> "$HOME/Documents/FantasyBaseballApplications/\
Output/${teams[$i-1]}"
  echo "" >> "$HOME/Documents/FantasyBaseballApplications/\
Output/${teams[$i-1]}"
  python3 $HOME/Documents/FantasyBaseballApplications/test.py $i P sum >> "$HOME/Documents/FantasyBaseballApplications/\
Output/${teams[$i-1]}"
  python3 $HOME/Documents/FantasyBaseballApplications/test.py $i P list >> "$HOME/Documents/FantasyBaseballApplications/\
Output/${teams[$i-1]}"
done

positions=( B C 1B 2B 3B SS OF P SP RP )

for i in {0..9}
do
  python3 $HOME/Documents/FantasyBaseballApplications/test.py A ${positions[$i]} list > "$HOME/Documents/\
FantasyBaseballApplications/Output/${positions[$i]}"
done

date > "$HOME/Documents/FantasyBaseballApplications/Output/LastModified"
